### ISSUE TITLE
"./MATLAB/OFDM_TX_bit_symbols_Len.txt"

### ISSUE THREAD

**Issue by jinsanko** [phthinh/OFDM_802_11#1]
I am looking for a file which is mentioned in your OFDM_TX_tb.v.
Thank.

Best regards

Jinsan Ko

**Comment by phthinh** [comment]
Hi Junsan Ko,

This file is generated by Matlab script named "OFDM_TX_wr_dat_in.m"  together with other .txt files, i. e., OFDM_TX_bit_symbols.txt, RTL_OFDM_TX_bit_symbols.txt for the testbench and Pre.txt, Pilot_seq.txt for hardware implementation.

Regards,
Thinh

**Comment by jinsanko** [comment]
Thank.

**Comment by jinsanko** [comment]
Thank.
