### ISSUE TITLE
fscanf problem

### ISSUE THREAD

**Issue by jinsanko** [phthinh/OFDM_802_11#2]
In OFDM_TX_tb.v line 81 and 82,
		para_fin = $fopen("./MATLAB/OFDM_TX_bit_symbols_Len.txt","r");
		$fscanf(para_fin, "%d ", Len);                                               <--- line 81
		$fscanf(para_fin, "%d ", NLOP);
		$fclose(para_fin);
My Modelsim "Expected a system task, not a system function '$fscanf'"
Any idea on how to modiy the code?

Thank.

Best regards
Jinsan Ko

**Comment by phthinh** [comment]
It may be that the file is not open properly. Can you check the file path and make sure it can be read by testbench in Modelsim?

Regards,
Thinh
