### ISSUE TITLE
Simulation of receiver

### ISSUE THREAD

**Issue by jituhyanki** [phthinh/OFDM_802_11#3]
Hi
I am taking it as reference. I wanted to know that what is the processing clock in receiver for sample rate of 10msps.
Regards
J S Hyanki

**Comment by phthinh** [comment]
Hi Hyanki,
The receiver is designed with a  stream processing architecture, the processing clock should be as fast as the sample rate (e.g. 10msps). Certainly, there is processing latency but I am not able to remember the exact latency, you can do RTL simulation to get this value.
